  
services:
    
   # Postgres -----------------------------------------------------
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # Persist data, avoid data loss on container restart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  # Ollama --------------------------------------------------------- 
  ollama:
    image: ollama/ollama # Use the official Ollama image
    container_name: ollama
    restart: unless-stopped
    volumes:
      - /home/jip.wulffele@Digital-Grenoble.local/.ollama/models:/root/.ollama/models # Map local models directory
    ports:
      - "11435:11434"  # Host port mapping

  # Flask ---------------------------------------------------------
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://flaskuser:flaskpass@db:5432/flaskdb
    depends_on:
      - ollama
      - db
    volumes:
      - ./static/uploads:/app/static/uploads

# Volumes --------------------------------------------------------
volumes:
  ollama_data:
  postgres_data:


# Useful commands ------------------------------------------------

# Clear postgres table:
# docker ps -aq | xargs docker stop
# docker ps -aq | xargs docker rm
# docker compose down -v

# If cache problems:
# docker builder prune --force
# docker system prune

# Build and run containers:
# docker compose up --build

# Acess container when docker compose is up (from other therminal):
# docker exec -it <ID> /bin/bash
# Find localtion ollama models:
# find / -name models | grep "ollama"